name: actual
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^6.0.0
  go_router: ^4.3.0
  json_annotation: ^4.6.0
  retrofit: ^3.0.1+1
  skeletons: ^0.0.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1

flutter:
  uses-material-design: true

  assets:
    - asset/fonts/
    - asset/img/misc/
    - asset/img/food/
    - asset/img/logo/
    - asset/rive/
    - asset/svg/icon/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.otf
          weight: 100
